modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="More Chest Variants - Biome Makeover"
authors="${mod_authors}"
description='''This adds the Biome Makeover mod's Wood types to More Chest Variats
Expanding the colour'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="lolmcv"
    mandatory=true
    versionRange="${lolmcv_version_range}"
    ordering="NONE"
    side="BOTH"